server:
  port: 9090
spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/bookings?createDatabaseIfNotExist=true
    username: root
    password: Danvi@02
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true